name: Code check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Biome, Typescript and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type check
        run: npm run typecheck
      - name: Format
        run: npm run format:check
      - name: Tests
        run: npm run test
